// Package shell builds the per-profile launcher functions that
// `aiacc shell-init` emits. Each function runs the provider's CLI with the
// profile's config directory selected via an environment variable — e.g.
// `claude-work` runs `CLAUDE_CONFIG_DIR=<dir> claude`.
//
// The directory value is embedded in a function definition the user's shell
// sources, so it is the injection surface: directory values and identifiers are
// validated and single-quote escaped here before they reach a shell.
package shell

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	// ErrUnknownShell is returned for a shell aiacc does not support.
	ErrUnknownShell = errors.New("unknown shell")
	// ErrUnsafeDir is returned when the directory is empty or contains a control
	// character that could corrupt or escape the emitted statement.
	ErrUnsafeDir = errors.New("unsafe directory value")
)

var (
	// envVarRe matches a POSIX shell identifier.
	envVarRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)
	// aliasNameRe matches a launcher function name: a letter/underscore start,
	// then letters, digits, hyphens, or underscores.
	aliasNameRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]*$`)
	// cmdRe matches a bare command token (no spaces or shell metacharacters).
	cmdRe = regexp.MustCompile(`^[A-Za-z0-9_.+-]+$`)
)

// Launcher returns a shell function that launches command with envVar pointed at
// dir — the profile launcher `aiacc shell-init` emits, e.g.
//
//	claude-work() { CLAUDE_CONFIG_DIR='/home/x/.claude-work' command claude "$@"; }
//
// Poka-yoke: when name, command, or envVar is not a safe token it returns ""
// with no error, so the caller skips that profile silently — a malformed name is
// never written into a script the shell sources. An unsafe dir (control chars)
// is a hard error. dir is single-quote escaped so it cannot break out.
func Launcher(shellName, name, command, envVar, dir string) (string, error) {
	if !aliasNameRe.MatchString(name) || !cmdRe.MatchString(command) || !envVarRe.MatchString(envVar) {
		if shellName != "bash" && shellName != "zsh" && shellName != "fish" {
			return "", ErrUnknownShell
		}
		return "", nil
	}
	if err := validateDir(dir); err != nil {
		return "", err
	}
	switch shellName {
	case "bash", "zsh":
		return fmt.Sprintf("%s() { %s=%s command %s \"$@\"; }\n",
			name, envVar, posixSingleQuote(dir), command), nil
	case "fish":
		return fmt.Sprintf("function %s; env %s=%s %s $argv; end\n",
			name, envVar, fishSingleQuote(dir), command), nil
	default:
		return "", ErrUnknownShell
	}
}

// RcPath is the conventional startup file for a shell, absolute. It does not
// check whether the file exists — callers create it on write.
func RcPath(shellName string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	switch shellName {
	case "bash":
		return filepath.Join(home, ".bashrc"), nil
	case "zsh":
		return filepath.Join(home, ".zshrc"), nil
	case "fish":
		return filepath.Join(home, ".config", "fish", "config.fish"), nil
	default:
		return "", ErrUnknownShell
	}
}

// LauncherScript returns an executable POSIX-sh script that launches command
// with envVar pointed at dir — the on-PATH launcher aiacc installs, so a command
// like `claude-work` works in any shell with no sourcing or reload. dir is
// single-quote escaped so a hostile value can't break out.
func LauncherScript(command, envVar, dir string) (string, error) {
	if !cmdRe.MatchString(command) || !envVarRe.MatchString(envVar) {
		return "", ErrUnknownShell
	}
	if err := validateDir(dir); err != nil {
		return "", err
	}
	return "#!/bin/sh\n" +
		"# generated by aiacc — do not edit; re-run `aiacc setup`\n" +
		"exec env " + envVar + "=" + posixSingleQuote(dir) + " " + command + " \"$@\"\n", nil
}

// PathLine is the line that adds dir to PATH in a shell startup file, used only
// as a fallback when no writable directory is already on PATH.
func PathLine(shellName, dir string) (string, error) {
	switch shellName {
	case "fish":
		return "fish_add_path " + fishSingleQuote(dir), nil
	case "bash", "zsh":
		return "export PATH=" + posixSingleQuote(dir) + `:"$PATH"`, nil
	default:
		return "", ErrUnknownShell
	}
}

// validateDir rejects empty input and any byte below 0x20 (control characters),
// which are unsafe for a sourced statement.
func validateDir(dir string) error {
	if dir == "" {
		return ErrUnsafeDir
	}
	for i := 0; i < len(dir); i++ {
		if dir[i] < 0x20 {
			return ErrUnsafeDir
		}
	}
	return nil
}

// posixSingleQuote wraps s in single quotes for bash/zsh, replacing each embedded
// single quote with the close-quote / escaped-quote / reopen-quote idiom.
// Backslashes are literal inside POSIX single quotes, so the quote is the only
// character that needs handling.
func posixSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// fishSingleQuote wraps s in single quotes for fish. fish treats backslash as an
// escape inside single quotes, so backslashes are doubled first; otherwise a
// value ending in a backslash could escape the quoting. Then single quotes are
// escaped as \'.
func fishSingleQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "'", `\'`)
	return "'" + s + "'"
}
